_chapters/lambdacalculus.md
students mostly come having done python  previously where they are called lambda functions
=> add mention of python

_chapters/javascript1.md
Hey Tim, I noticed that there was some code missing from the objects section. I'm not sure if what I added is helpful, but just wanted to let you know that you may want to check this part out.
=> Added missing code under Objects section

_chapters/functionaljavascript.md, _chapters/javascript1.md
I found students had trouble making the transition to using an object in a reduce call (for workshop computeBounds exercise).  Reviewing the course notes and tutes, students haven't really seen reduce used other than to sum numbers.  I thought it might be useful to have some extra examples in the course notes.  Of course there is a discussion to be had about whether this is too much handholding.
Edit:  Added some small formatting commits.
=> Suggestion to add some reduce examples to the Javascript Introduction

_chapters/functionaljavascript.md
#12
i think this is correct? i cant seem to test it from my branch
=> fix link again

_chapters/functionaljavascript.md
Hey Tim,
Just correct some grammar mistakes!
Cheers,
Nitin
=> Minor corrections (non-content related)

_chapters/haskell1.md, _chapters/purescript.md
=> Fix grammar

_chapters/haskell2.md
Hey Tim,
Noticed that there were a few broken links on this week's notes. This should fix them :)
=> Fix broken links in haskell2 notes

_chapters/higherorderfunctions.md, _chapters/javascript1.md
Hi Tim,
I've started looking at your lecture notes and made some minor edits. This is more or less a practice pull request for future potential contributions.
=> typos and minor edits

_chapters/functionaljavascript.md, _chapters/typescript1.md, _sass/main.scss
Hi Tim,
some more minor edits.
Please check if I am correct about your binary search having off-by-one errors. I didn't test the code, but from looking at it I'm pretty sure I'm right. (I have been known to make mistakes, though ;-).)
=> minor edits and minor off-by-one error

_chapters/typescript1.md
V is not yet declared for List\<T\>.
=> Missing generic for reduce in ts exercises

_chapters/haskell4.md, _chapters/monad.md, _chapters/parsercombinators.md
another batch of small edits. Mostly punctuation etc, but a few actual content corrections.
=> various small edits.

_chapters/haskell3.md, _chapters/parsercombinators.md
Maybe? Depending on tutorial update :)
=> alternatives?

_chapters/haskell2.md
Correct unclosed code block showcasing the usage on `data` and `newtype` keyword.
=> Correct unclosed codeblock

_chapters/functionaljavascript.md
=> Fix typo in code

_chapters/haskell1.md
=> Fix whitespace and syntax highlighting and things

_chapters/asteroids.md
- Change `e.direction` to `this.direction` and `e.on` to `this.on`
=> Fix typo in asteroids page

_chapters/eithers.md, _chapters/haskell4.md
Also removed exercises being listed twice
=> Fix typos in haskell4.md and formatting in eithers.md

_plugins/glossary.rb
=> Fix glossary.rb removing HTML tags

_chapters/functionaljavascript.md
Might be a bit too much but I marked it as optional and I thought it was a cool use of continuations.
=> add some optional stuff about CPS and tail recursion

_chapters/functionaljavascript.md
credits to https://edstem.org/au/courses/25517/discussion/2812142 for pointing this out
=> fix factorialCPS function

_chapters/asteroids.md
Fix typo (?) 
I think ship should rotate 100 degrees per second instead of times per second
=> Change 100 times per second to 100 degres per second

_chapters/haskell0.md, _chapters/haskell1.md
`stack config set snapshot` instead of manually editing files
=> simplify haskell installation instructions

_chapters/haskell0.md
Not entirely sure what the error is - the GHCup troubleshooting page says that the script will immediately exit
=> add note about antivirus for haskell installation
