_chapters/javascript1.md

In at least the "Introduction to JavaScript" chapter, code keywords such
as `let`, `const` and `this` are not consistently rendered as inline
code due to missing backticks. Sometimes, triple backticks (which work)
are used even though the code is inline.
I also amended line 337 to consistently blockquote the output.
Hopefully this improves readability to some degree, particularly when
referring to keywords such as `this` which can "blend in" otherwise.

javascript1: consistently use single backticks for inline code

---

_chapters/javascript1.md

Since we're told not to use `var`, it would be better not to include them in examples.

Replaced use of var to const in polymorphism code example.

---

_chapters/haskell3.md

f x = 1 + x
f x = (1+) x
f = (+)    // this should be  f = (1+)

fix eta conversion typo

---

_chapters/haskell3.md

The example for the succinct output exercise renders poorly at https://tgdwyer.github.io/haskell3/ and introduces an annoying horizontal scrollbar for the whole page.
This fixes it so there is a horizontal scrollbar only on the example block itself.

Fix horizontal scrollbar in haskell3

---

_chapters/typescript1.md

I found the examples of Readonly<T> slightly confusing to read as it wasn't immediately clear that `studentVersion1:ImmutableStudent` is a new variable called studentVersion1 and not some modification of the original. Changing the `as const` declaration to version 2 and the Readonly<T> declaration to version 3 shows these are new variables. 
Also added a space after the colon to be consistent with other variable declarations.
This change may require a new screenshot of the 'squiggly' to match these code changes.

Small clarification in typescript.md

---

_chapters/lambdacalculus.md

* In your initial description of beta reduction syntax I had never seen the first example anywhere else, including in the rest of the notes. I updated it to be inline with the Wikipedia syntax you link to and your usage elsewhere in the notes.
* I added a short introduction to the church encoding of natural numbers since it would feature prominently alongside church booleans in the assignment.

Updating Lambda Calculus Notes

---

_config.yml
_data/chapters.yml

Whether or not the URL has a final slash, it redirects to the version with the final slash.
This fixes 404 errors that result from links that were made prior to the permalink policy unification.

Made URLs with/without final slash work

---

_chapters/asteroids.md

I believe the type of this argument should be of the Event type defined just above, not string type

Incorrect type for eventName

---

_chapters/haskell2.md
_chapters/haskell3.md

Minor edits.
I'm not sure whether I agree with the sentence ”This granularity allows the type system to guard against improper use of numbers that might result in loss in precision or division by zero.“ in haskell2.md. Don't see how these typeclasses guard against division by zero.

minor edits.

---

_chapters/parsercombinators.md

Replaced "arithetic" with "arithmetic"

Fix typo in parsercombinators.md

---

_chapters/higherorderfunctions.md
_data/chapters.yml
_data/glossary.yml
_plugins/glossary.rb
_sass/main.scss

This PR fixes this glossary issue:
This happened whenever a glossary term was a substring of another one (e.g. ‘K-Combinator’ and ‘Combinator’). ‘K-Combinator’ would generate HTML including `<span data-term="k-combinator">`, and then the `combinator` in `data-term="k-combinator"` would get replaced with another glossary term `<span>`.
I also fixed this issue:
(thanks @harry-breslin for pointing out this issue)

Fix glossary (again)

---

_chapters/functionaljavascript.md

There are some typos in the "more verbose" definition of `map`.

Fix typos in functionaljavascript.md

---

_chapters/typescript1.md

add missing key parameter line 410; clarifies the use of binarySearch3().

binarySearch3() missing key parameter

---

_chapters/functionalreactiveprogramming.md

This is to avoid confusion with `concatMap` for observables, which is different from `mergeMap`.

remove ‘AKA concatMap’ in mergeMap comment

---

_chapters/asteroids.md

I may be mistaken, but wouldn't scaling the added velocity of the bullet by -2 result in it firing "backwards" (relative to the velocity of the ship)? For example, assuming linear motion:
- If ship.vel < unitVecInDirection * 2, bullet fires in opposite direction that ship is pointing in
- If ship.vel == unitVecInDirection * 2, bullet has zero velocity (i.e., is stationary)
- If ship.vel > unitVecInDirection * 2, bullet fires in same direction but with slower speed, appears to travel backwards w.r.t. ship
This velocity value also appears to be inconsistent with the StackBlitz implementation:
https://stackblitz.com/edit/asteroids2023?file=src%2Fstate.ts%3AL107:
```ts
class Shoot implements Action {
apply = (s: State) => ({ ...s,
bullets: s.bullets.concat([
((unitVec: Vec) =>
createBullet
({ …
```

Fix bullet velocity

---

_includes/header.html
_sass/minima/custom-styles.scss

Fix a couple of the issues from the Minima v3 update (#121):
1. Fix the solutions button from
to
2. Fix dark mode colours (e.g. cheatsheets and glossary) from
to

fix dark mode colours

---

_chapters/haskell2.md

Escaped `|` character to avoid this

Fix haskell2.md typo + formatting

---

_chapters/parsercombinators.md

replaced `f` unary function with `predicate`

fixed the `satisfy` parser to handle predicates

---

_chapters/javascript1.md

I noticed some of the JavaScript code examples use semicolons and some do not...
- Added consistent semicolons to JavaScript code examples in the **JavaScript Introduction** chapter.
- The changes improve code style consistency throughout the chapter and align with standard JavaScript style conventions.
Although it's optional to use semicolons in JS, it's probably better to stick to one style.

add consistent semicolons to JS code examples in javascript1.md

---

_chapters/functionaljavascript.md

Add a h2 heading to the bottom of functionaljavascript.md to mark the beginning of the Glossary for consistent formatting with other chapters

Add Glossary heading to functionaljavascript.md

---

_chapters/haskell4.md

You would think the word is "aggregatable" but it's actually "aggregable" (I blame the French)
https://www.merriam-webster.com/dictionary/aggregable

English is a terrible language ("aggregatable" isn't a word)
